version: '3.4'

services:
  dacpacexample:
    container_name: dacpac-api
    image: ${DOCKER_REGISTRY-}dacpacapiexample
    environment:
      SQLSERVER_HOST: "sqlserver"
      SQLSERVER_SA_PASSWORD: "SecureP4ssW0rd"
      SQLSERVER_DATABASE: "ProductsDb"
    ports:  
      - '44386:443'  
    expose:  
      - 44386
    networks:
      - default
    build:
      context: .
      dockerfile: Dockerfile

  databaselcontainer:
    container_name: dacpac-database
    image: ${DOCKER_REGISTRY-}dacpacdatabaseexample
    networks:
      - default
    build:
      context: .
      dockerfile: Dockerfile.Database
      args:
        DB_SERVER: "192.168.201.81,1433"
        DB_PASSWORD: "SecureP4ssW0rd"
        DB_NAME: "ProductsDb"
        ACCEPT_EULA: "Y"

networks:
  default:
    external:
      name: databasecontainer_default