version: '3.8'

services:
  dacpacapiexample:
    container_name: api
    image: ${DOCKER_REGISTRY-}dacpacapiexample
    links:
      - sqlserverservice
    environment:
      SQLSERVER_HOST: "sqlserver"
      SQLSERVER_SA_PASSWORD: "SecureP4ssW0rd"
      SQLSERVER_DATABASE: "ProductsDb"
    ports:  
      - '44325:443'  
    expose:  
      - 44325
    build:
      context: .
      dockerfile: Dockerfile

  sqlserverservice:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "SecureP4ssW0rd"
      ACCEPT_EULA: "Y"
    volumes:  
      - ./data/mssql:/var/opt/mssql3
      - ./backups:/backups
      - ./scripts:/scripts
    entrypoint: 
      - ./scripts/entrypoint.sh   
    ports:  
      - '1433:1433'  
    expose:  
      - 1433