version: '3.4'

services:
  databaselcontainer:
    container_name: davpac-database
    networks:
      - default
    build:
      context: .
      dockerfile: Dockerfile.Database
      args:
        DB_SERVER: "192.168.201.81,1433"
        DB_PASSWORD: "SecureP4ssW0rd"
        DB_NAME: "ProductsDb"
        ACCEPT_EULA: "Y"

  davpacexample:
    container_name: davpac-api
    image: ${DOCKER_REGISTRY-}davpacexample
    environment:
      SQLSERVER_HOST: "sqlserver"
      SQLSERVER_SA_PASSWORD: "SecureP4ssW0rd"
      SQLSERVER_DATABASE: "ProductsDb"
    ports:  
      - '6002:443'  
    expose:  
      - 6002
    networks:
      - default
    build:
      context: .
      dockerfile: Dockerfile

networks:
  default:
    external:
      name: databasecontainer_default